nelmio_api_doc:
    documentation:
        info:
            title: Atrio persons
            description: Application des équipes atrio
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
